name: Generate Jekyll Archives
# description: Generate categories, tags and years archive files.
on:
  workflow_dispatch:
  push:
    paths:
      - "_posts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Jekyll Archives
        uses: actions/setup-ruby@v1
      - name: Install dependencies
        run: pip install jekyll-archives

      - name: Generate Jekyll Archives
        run: |
          jekyll build

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"          
          git config user.email "<>"          

      - name: commit
        run: |
          git add --all
          git commit -m "Created and updated archive files." || echo "No changes to commit."
          git push || echo "No changes to push."
